name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Start Kubernetes minikube
        uses: medyagh/setup-minikube@master
      - name: Try the Kubernetes cluster
        run: kubectl get nodes
      - name: Build and test
        working-directory: rentalService
        run: |
          export SHELL=/bin/bash
          ./gradlew build
          docker build -f ./Dockerfile -t local/rentalservice:1 .
          docker images
          cd ..
      - name: Deploy the image to minikube
        run:
          kubectl apply -f deployment.yml
      - name: Get Kubernetes service URL
        run: |
          kubectl get pods
          kubectl wait --for=condition=ready pod -l app=rentalservice
          minikube service list
          minikube service rentalservice --url
          echo "------------------opening the service------------------"
      - name: Test Kubernetes service URL
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 10
          max_attempts: 4
          command: curl $(minikube service rentalservice --url)/cars
      - name: Log Kubernetes pods
        run: |
          kubectl logs $(kubectl get pods -l app=rentalservice -o name)